#!/bin/bash
set -e
set -o pipefail

cd $(dirname $0)

CONFIG_DIR=${XDG_CONFIG_HOME:-~/.config}/exodus-gw-dev

use_sidecar(){
  # are we on a network where this can be used?
  host images.paas.redhat.com &>/dev/null
}

check_prereqs(){
  failed=0
  for cmd in podman sscg tox host hostname postgres; do
    if ! test -x /usr/bin/$cmd; then
      failed=1
      echo "ERROR: not available: $cmd (try: 'sudo dnf install /usr/bin/$cmd')" 1>&2
    fi
  done

  if test $failed -eq 1; then
    echo "ERROR: missing packages. Install packages listed above, then try again." 1>&2
    exit 50
  fi
}

enable_units(){
  systemctl --quiet --user enable $PWD/exodus-gw.target

  systemctl --user enable $PWD/exodus-gw-db.service
  systemctl --user enable $PWD/exodus-gw-localstack.service
  systemctl --user enable $PWD/exodus-gw-uvicorn.service
  systemctl --user enable $PWD/exodus-gw-worker.service
  systemctl --user enable $PWD/exodus-gw-cert.service

  if use_sidecar; then
    systemctl --user enable $PWD/exodus-gw-sidecar.service
  else
    echo "WARNING: sidecar image appears to be unavailable, cannot use HTTPS." 1>&2
  fi
}

create_env_file(){
  # Create a .env file read by the rest of the units via EnvironmentFile.
  # The main reason we need to do this is to ensure an accurate source path,
  # since not every dev may clone the repo to the same location.
  if ! test -f ~/.config/exodus-gw-dev/.env; then
    mkdir -p ~/.config/exodus-gw-dev
    cat >~/.config/exodus-gw-dev/.env <<END
# Environment for exodus-gw development services.
#
# Arbitrary environment variables can be set here.
# The most commonly used are listed here as examples.

# Path to git repo
EXODUS_GW_SRC_PATH=$(realpath -L ../..)

# Port numbers for various things. You might have to change these
# if you're having a clash with other services.
#EXODUS_GW_DB_SERVICE_PORT=3355
#EXODUS_GW_LOCALSTACK_PORT=3377
#EXODUS_GW_HTTP_PORT=8000
#EXODUS_GW_HTTPS_PORT=8010

# You'll have to change this too if you change the localstack port.
#EXODUS_GW_S3_ENDPOINT_URL=https://localhost:3377

# Disable migrations during development
#EXODUS_GW_DB_MIGRATION_MODE=model

# Drop and recreate tables on restart
#EXODUS_GW_DB_RESET=true
END
  fi

}

make_cert(){
  systemctl --user start exodus-gw-cert.service
}

summarize(){
  cat <<END
exodus-gw units are installed!

Suggested commands:

  # Start development servers
  systemctl --user start exodus-gw.target

  # Observe server logs
  journalctl --user '--unit=exodus-gw-*' -f

  # Verify http server is working
  curl http://localhost:8000/healthcheck

  # Verify background worker is running
  curl http://localhost:8000/healthcheck-worker

  # Create a test bucket in localstack
  aws --endpoint-url=http://localhost:3377 s3api create-bucket --bucket test

  # Install CA certificate to system bundle
  sudo cp $CONFIG_DIR/ca.crt /etc/pki/ca-trust/source/anchors/exodus-gw-dev.crt
  sudo update-ca-trust
END

  if use_sidecar; then
    cat <<END

  # Verify https server is working
  curl https://localhost:8010/healthcheck
END
  fi
}

run(){
  check_prereqs
  create_env_file
  enable_units
  make_cert
  summarize
}

run
