FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:82fad27b91361473d919522a01a1198f327230bf8d2b569a8995bdcd6ac7cb94

# Add sources
COPY . /usr/local/src/exodus-gw/

# Install extra requirements specific to container deployment
RUN \
    # Install shadow-utils for adduser functionality
    microdnf -y install shadow-utils \
    # Install extra commands needed for build
    && microdnf -y install python3.11 python3.11-devel python3.11-pip gcc make \
    # Install packages needed for psycopg2 installation
    && microdnf -y install postgresql-devel \
    # Ensure packages are up-to-date 
    && microdnf -y update \
    # Install application itself
    && cd /usr/local/src/exodus-gw \
    && pip3.11 install --require-hashes -r requirements.txt \
    && pip3.11 install --no-deps . \
    # Clean up unnecessary data
    && microdnf clean all && rm -rf /var/cache/yum && rm -rf /usr/local/src/exodus-gw

# Run as a non-root user
RUN adduser exodus-gw
USER exodus-gw

# Enable communication via port 8080
EXPOSE 8080

# Run the application
ENTRYPOINT ["gunicorn", \
    "-k", "uvicorn.workers.UvicornWorker", \
    "--bind", "0.0.0.0:8080", \
    "--keep-alive", "30", \
    "exodus_gw.main:app"]
