FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:67fee1a132e8e326434214b3c7ce90b2500b2ad02c9790cc61581feb58d281d5

# Add sources
COPY . /usr/local/src/exodus-gw/

# Install extra requirements specific to container deployment
RUN \
    # Install shadow-utils for adduser functionality
    microdnf -y install shadow-utils \
    # Install extra commands needed for build
    && microdnf -y install python3.12 python3.12-devel python3.12-pip gcc make \
    # Install packages needed for psycopg2 installation
    && microdnf -y install postgresql-devel \
    # Ensure packages are up-to-date 
    && microdnf -y update \
    # Install application itself
    && cd /usr/local/src/exodus-gw \
    && pip3.12 install --require-hashes -r requirements.txt \
    && pip3.12 install --no-deps . \
    # Clean up unnecessary data
    && microdnf clean all && rm -rf /var/cache/yum && rm -rf /usr/local/src/exodus-gw

# Run as a non-root user
RUN adduser exodus-gw
USER exodus-gw

# Enable communication via port 8080
EXPOSE 8080

# Run the application
ENTRYPOINT ["gunicorn", \
    "-k", "uvicorn.workers.UvicornWorker", \
    "--bind", "0.0.0.0:8080", \
    "--keep-alive", "30", \
    "exodus_gw.main:app"]
