"""Add dramatiq messages and consumers

Revision ID: 0a3a709da247
Revises: cd561983acb2
Create Date: 2021-02-11 13:54:23.787714

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0a3a709da247"
down_revision = "cd561983acb2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dramatiq_consumers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("last_alive", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dramatiq_messages",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("consumer_id", sa.String(), nullable=True),
        sa.Column("queue", sa.String(), nullable=False),
        sa.Column(
            "body", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dramatiq_messages")
    op.drop_table("dramatiq_consumers")
    # ### end Alembic commands ###
