"""Initial migration

Revision ID: 0c60e1b25e03
Revises:
Create Date: 2021-02-04 11:40:35.174516

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.types import Uuid

# revision identifiers, used by Alembic.
revision = "0c60e1b25e03"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Because this is the first migration, we have no idea what's the state of the
    # DB in this environment, so we will do a one-time unconditional drop of tables
    # at the beginning.
    op.execute("DROP TABLE IF EXISTS items")
    op.execute("DROP TABLE IF EXISTS publishes")

    # ### commands auto generated by Alembic ###
    op.create_table(
        "publishes",
        sa.Column("id", Uuid(as_uuid=False), nullable=False),
        sa.Column("env", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "items",
        sa.Column("id", Uuid(as_uuid=False), nullable=False),
        sa.Column("web_uri", sa.String(), nullable=False),
        sa.Column("object_key", sa.String(), nullable=False),
        sa.Column("from_date", sa.String(), nullable=False),
        sa.Column("publish_id", Uuid(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["publish_id"],
            ["publishes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_table("items")
    op.drop_table("publishes")
    # ### end Alembic commands ###
