#!/usr/bin/env python3
# Helper script to generate openapi JSON file
# during publishing of docs.
import json

from exodus_gw.main import app

api = app.openapi()

with open("docs/openapi/openapi.json", "wt") as f:
    json.dump(api, f)
