#!/usr/bin/env python3
# Helper script to generate openapi JSON file
# during publishing of docs.
import os
import json

from exodus_gw import application

api = application.openapi()

with open("docs/openapi/openapi.json", "wt") as f:
    json.dump(api, f)
