#!/bin/sh
#
# Create an s3 bucket in the dev env's localstack instance.
#
# You will need to run this when:
# - initially creating the dev env, or
# - after cleaning it, or
# - if you want to use a different bucket
#

# should match bucket for the environment you want to use in exodus-gw.ini
BUCKET_NAME="${1:-my-bucket}"

ENV_FILE="~/.config/exodus-gw-dev/.env"

if test -f "$ENV_FILE"; then
  . "$ENV_FILE"
fi

set -xe

exec aws \
  --endpoint-url="${EXODUS_GW_S3_ENDPOINT_URL:-https://localhost:3377}" \
  s3api \
  create-bucket \
  --bucket "${BUCKET_NAME}"
