name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install tox

    - name: Build docker image
      run: |
        docker --version
        docker build . -f openshift/containers/exodus-gw/Containerfile

    - name: Run bandit test
      run: tox -e bandit

    - name: Run auto-tests
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: tox -e cov-ci

    - name: Run static analysis
      run: tox -e static

    - name: Build documentation
      run: tox -e docs

    - name: Publish documentation
      if: ${{ success() }}
      env:
        GITHUB_TOKEN: ${{ secrets.DOCS_TOKEN }}
      run: scripts/push-docs
